import os
import shutil
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="S.A.G.A. Asset Foundry", description="Dynamic AI Asset Server")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Directory to store generated assets
ASSETS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "storage")
os.makedirs(ASSETS_DIR, exist_ok=True)

# MOUNT PUBLIC DIRECTORY
PUBLIC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "public")

# Mount the storage directory and public directory
app.mount("/assets", StaticFiles(directory=ASSETS_DIR), name="assets")
app.mount("/public", StaticFiles(directory=PUBLIC_DIR), name="public")

BIOME_MAP = {
    "FOREST": "/public/floor/grass_full_new.png",
    "JUNGLE": "/public/floor/bog_green_0_new.png",
    "RUINS": "/public/tiles/floor_stone.png",
    "MOUNTAIN": "/public/floor/floor_sand_rock_0.png",
    "DUNGEON": "/public/floor/crypt_10.png",
    "DESERT": "/public/floor/sand_1.png",
    "WASTELAND": "/public/floor/grey_dirt_0_new.png",
    "SWAMP": "/public/floor/swamp_0_new.png",
    "TUNDRA": "/public/floor/ice_0_new.png",
    "CAVERN": "/public/floor/floor_sand_stone_0.png"
}

OBJ_MAP = {
    "TREE": "/public/trees/tree_1_red.png",
    "WALL": "/public/tiles/wall_stone.png",
    "WATER": "/public/water/shallow_water.png",
    "ROCK": "/public/floor/pebble_brown_0_new.png",
    "BARREL": "/public/objects/barrel.png",
    "CRATE": "/public/objects/crate.png",
    "TABLE": "/public/objects/table.png",
    "CHEST": "/public/objects/chest.png"
}

@app.get("/api/assets/map/{category}/{key}")
def get_asset_mapping(category: str, key: str):
    key = key.upper()
    if category == "biome":
        return {"url": f"http://localhost:8012{BIOME_MAP.get(key, '/public/floor/grass_0_new.png')}"}
    if category == "object":
        return {"url": f"http://localhost:8012{OBJ_MAP.get(key, '/public/objects/barrel.png')}"}
    return {"error": "Category not found"}

class AssetRegister(BaseModel):
    asset_id: str
    source_path: str # Path to the image generated by the AI tool

@app.get("/health")
def health():
    return {"status": "ok", "module": "Asset Foundry", "port": 8012}

@app.post("/api/assets/register")
async def register_asset(reg: AssetRegister):
    """
    Copies an AI-generated image to the foundry storage and returns the public URL.
    """
    if not os.path.exists(reg.source_path):
        raise HTTPException(status_code=404, detail="Source image not found")
    
    file_ext = os.path.splitext(reg.source_path)[1]
    target_filename = f"{reg.asset_id}{file_ext}"
    target_path = os.path.join(ASSETS_DIR, target_filename)
    
    try:
        shutil.copy2(reg.source_path, target_path)
        return {"url": f"http://localhost:8012/assets/{target_filename}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to copy asset: {str(e)}")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8012)
