from pymilvus import (
    CollectionSchema, FieldSchema, DataType,
)
# Schema definitions
ENTITY_SCHEMA = CollectionSchema(
    fields=[
        FieldSchema(
            name="uid",
            dtype=DataType.VARCHAR,
            max_length=200,
            is_primary=True,
            default_value=""
        ),
        FieldSchema(
            name="action_uid",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="action_label",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="target_uid",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="target_label",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="location_uid",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="location_label",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="resource_value",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=0
        ),
        FieldSchema(
            name="state",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="state_level",
            dtype=DataType.VARCHAR,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="timestamp",
            dtype=DataType.INT64,
            max_length=200,
            default_value=""
        ),
        FieldSchema(
            name="context",
            dtype=DataType.VARCHAR,
            max_length=2048,
            default_value=""
        ),
        FieldSchema(
            name="vector",
            dtype=DataType.FLOAT_VECTOR,
            dim=3072
        ),
        FieldSchema(
            name="strategy",
            dtype=DataType.VARCHAR,
            max_length=2048,
            default_value=""
        ),
        FieldSchema(
            name="history",
            dtype=DataType.VARCHAR,
            max_length=4096,
            default_value=""
        ),
    ],
    description="Entity memory storage"
)