"""Initial database schema

Revision ID: 9a6d5baf6502
Revises: 
Create Date: 2025-08-09 23:53:39.845167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6d5baf6502'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('homebrew_rules', sa.JSON(), nullable=True),
    sa.Column('world_description', sa.Text(), nullable=True),
    sa.Column('world_art', sa.JSON(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('spells',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('casting_time', sa.String(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('higher_levels', sa.Text(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('concentration', sa.Boolean(), nullable=False),
    sa.Column('damage_dice', sa.String(), nullable=True),
    sa.Column('save_type', sa.String(), nullable=True),
    sa.Column('spell_lists', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_id'), 'spells', ['id'], unique=False)
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('personality', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_id'), 'npcs', ['id'], unique=False)
    op.create_table('npc_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('relationship_change', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_interactions_id'), 'npc_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npc_interactions_id'), table_name='npc_interactions')
    op.drop_table('npc_interactions')
    op.drop_index(op.f('ix_npcs_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.drop_index(op.f('ix_spells_id'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
